[package]
name = "trades-parser-cli"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono.workspace = true
clap = { workspace = true }
corporate-actions-parser.workspace = true
ecb-data-parser.workspace = true
trades-parser = { workspace = true }
meldefonds-corrections-parser = { workspace = true }
rust_decimal = { workspace = true }
serde.workspace = true
thiserror.workspace = true
csv.workspace = true
opening-positions-parser.workspace = true

[lints]
workspace = true
